In [1]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold
import pandas as pd

wine_data = load_wine(as_frame=True)
full_dataset = wine_data.frame

full_dataset.to_csv("wine_dataset.csv", index=False)

In [2]:
wine_data.DESCR

'.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 178\n:Number of Attributes: 13 numeric, predictive attributes and the class\n:Attribute Information:\n    - Alcohol\n    - Malic acid\n    - Ash\n    - Alcalinity of ash\n    - Magnesium\n    - Total phenols\n    - Flavanoids\n    - Nonflavanoid phenols\n    - Proanthocyanins\n    - Color intensity\n    - Hue\n    - OD280/OD315 of diluted wines\n    - Proline\n    - class:\n        - class_0\n        - class_1\n        - class_2\n\n:Summary Statistics:\n\n============================= ==== ===== ======= =====\n                                Min   Max   Mean     SD\n============================= ==== ===== ======= =====\nAlcohol:                      11.0  14.8    13.0   0.8\nMalic Acid:                   0.74  5.80    2.34  1.12\nAsh:                          1.36  3.23    2.36  0.27\nAlcalinity of Ash:            10.6  30.0    19.5   3.3\nMagnesium:                    70.0 162.0    99.7  14.3\nTotal Phenols:                0.98  3.88    2.29  0.63\nFlavanoids:                   0.34  5.08    2.03  1.00\nNonflavanoid Phenols:         0.13  0.66    0.36  0.12\nProanthocyanins:              0.41  3.58    1.59  0.57\nColour Intensity:              1.3  13.0     5.1   2.3\nHue:                          0.48  1.71    0.96  0.23\nOD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\nProline:                       278  1680     746   315\n============================= ==== ===== ======= =====\n\n:Missing Attribute Values: None\n:Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners:\n\nForina, M. et al, PARVUS -\nAn Extendible Package for Data Exploration, Classification and Correlation.\nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science.\n\n.. dropdown:: References\n\n    (1) S. Aeberhard, D. Coomans and O. de Vel,\n    Comparison of Classifiers in High Dimensional Settings,\n    Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Technometrics).\n\n    The data was used with many others for comparing various\n    classifiers. The classes are separable, though only RDA\n    has achieved 100% correct classification.\n    (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))\n    (All results using the leave-one-out technique)\n\n    (2) S. Aeberhard, D. Coomans and O. de Vel,\n    "THE CLASSIFICATION PERFORMANCE OF RDA"\n    Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of\n    Mathematics and Statistics, James Cook University of North Queensland.\n    (Also submitted to Journal of Chemometrics).\n'

In [3]:
X_train, X_test, y_train, y_test = train_test_split(wine_data.data, wine_data.target, stratify=wine_data.target, test_size=0.2, random_state=42)

In [4]:
X_train.shape

(142, 13)

In [5]:
y_train.head()

36     0
30     0
26     0
12     0
148    2
Name: target, dtype: int64

In [6]:
X_train.info()

summary = pd.DataFrame({
    "dtype": X_train.dtypes,
    "missing": X_train.isnull().sum(),
    "missing_friction": X_train.isna().mean(),
    "unique": X_train.nunique(),
})

summary

<class 'pandas.DataFrame'>
Index: 142 entries, 36 to 131
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       142 non-null    float64
 1   malic_acid                    142 non-null    float64
 2   ash                           142 non-null    float64
 3   alcalinity_of_ash             142 non-null    float64
 4   magnesium                     142 non-null    float64
 5   total_phenols                 142 non-null    float64
 6   flavanoids                    142 non-null    float64
 7   nonflavanoid_phenols          142 non-null    float64
 8   proanthocyanins               142 non-null    float64
 9   color_intensity               142 non-null    float64
 10  hue                           142 non-null    float64
 11  od280/od315_of_diluted_wines  142 non-null    float64
 12  proline                       142 non-null    float64
dtypes: float64(13)
memory usage: 15.5 KB

                                dtype  missing  missing_friction  unique
alcohol                       float64        0               0.0     104
malic_acid                    float64        0               0.0     107
ash                           float64        0               0.0      70
alcalinity_of_ash             float64        0               0.0      56
magnesium                     float64        0               0.0      49
total_phenols                 float64        0               0.0      82
flavanoids                    float64        0               0.0     110
nonflavanoid_phenols          float64        0               0.0      36
proanthocyanins               float64        0               0.0      87
color_intensity               float64        0               0.0     112
hue                           float64        0               0.0      69
od280/od315_of_diluted_wines  float64        0               0.0     104
proline                       float64        0               0.0     100

In [7]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyClassifier

models = {
    "dummy": DummyClassifier(strategy="most_frequent"),
    "logistic_regression": Pipeline([("scaler", StandardScaler()), ("model", LogisticRegression(random_state=42, max_iter=1000)),]),
}

In [9]:
from sklearn.model_selection import cross_val_score

res = []

for name, model in models.items():
    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="accuracy"
    )

    res.append({
        "model": name,
        "mean_accuracy": scores.mean(),
        "std": scores.std()
    })

pd.DataFrame(res)

                 model  mean_accuracy       std
0                dummy       0.401232  0.010256
1  logistic_regression       0.979064  0.027713

In [10]:
selected_model = models["logistic_regression"]
selected_model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [11]:
from sklearn.metrics import accuracy_score

selected_model.fit(X_train, y_train)
y_pred = selected_model.predict(X_test)

print(
    "Test accuracy:",
    accuracy_score(y_test, y_pred)
)

Test accuracy: 0.9722222222222222

In [12]:
scores = cross_val_score(
    selected_model,
    X_train,
    y_train,
    cv=cv,
)

print(scores)
print(scores.mean())
print(scores.std())

[0.93103448 1.         1.         1.         0.96428571]
0.9790640394088669
0.027713464392187602