In [27]:
from pathlib import Path
import pandas as pd
import urllib.request

def load_titanic_data():
    dataset_path = Path("datasets/titanic")

    train_path = dataset_path / "train.csv"
    test_path = dataset_path / "test.csv"

    if not train_path.is_file() or not test_path.is_file():
        dataset_path.mkdir(parents=True, exist_ok=True)

        base_url = (
            "https://raw.githubusercontent.com/"
            "ageron/handson-ml2/master/datasets/titanic/"
        )

        urllib.request.urlretrieve(
            base_url + "train.csv",
            train_path
        )

        urllib.request.urlretrieve(
            base_url + "test.csv",
            test_path
        )

    train_data = pd.read_csv(train_path)
    test_data = pd.read_csv(test_path)

    return train_data, test_data

titanic_train, titanic_test = load_titanic_data()

In [28]:
from pathlib import Path
import pandas as pd
import urllib.request

def load_titanic_data():
    path = Path("datasets/titanic/train.csv")

    if not path.is_file():
        path.parent.mkdir(parents=True, exist_ok=True)

        url = (
            "https://raw.githubusercontent.com/"
            "ageron/handson-ml2/master/datasets/titanic/train.csv"
        )

        urllib.request.urlretrieve(url, path)

    return pd.read_csv(path)

titanic_full = load_titanic_data()

In [30]:
y = titanic_full["Survived"]
X = titanic_full.drop("Survived", axis=1)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [36]:
X_train.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
692,693,3,"Lam, Mr. Ali",male,NaN,0,0,1601,56.4958,NaN,S
481,482,2,"Frost, Mr. Anthony Wood 'Archie'",male,NaN,0,0,239854,0.0000,NaN,S
527,528,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
855,856,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
801,802,2,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.0,1,1,C.A. 31921,26.2500,NaN,S

In [33]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 692 to 507
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Pclass       712 non-null    int64
 2   Name         712 non-null    str
 3   Sex          712 non-null    str
 4   Age          575 non-null    float64
 5   SibSp        712 non-null    int64
 6   Parch        712 non-null    int64
 7   Ticket       712 non-null    str
 8   Fare         712 non-null    float64
 9   Cabin        160 non-null    str
 10  Embarked     710 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 66.8 KB

In [34]:
X_train.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   712.000000  712.000000  575.000000  712.000000  712.000000  712.000000
mean    444.405899    2.308989   29.807681    0.492978    0.390449   31.819826
std     257.465527    0.833563   14.485223    1.060720    0.838134   48.059104
min       1.000000    1.000000    0.416700    0.000000    0.000000    0.000000
25%     222.750000    2.000000   21.000000    0.000000    0.000000    7.895800
50%     439.500000    3.000000   28.500000    0.000000    0.000000   14.454200
75%     667.250000    3.000000   39.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [35]:
X_train.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age            137
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          552
Embarked         2
dtype: int64

In [37]:
X = X.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"])

In [38]:
X.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S