In [7]:
from pathlib import Path
import pandas as pd
import urllib.request

def load_titanic_data():
    dataset_path = Path("datasets/titanic")

    train_path = dataset_path / "train.csv"
    test_path = dataset_path / "test.csv"

    if not train_path.is_file() or not test_path.is_file():
        dataset_path.mkdir(parents=True, exist_ok=True)

        base_url = (
            "https://raw.githubusercontent.com/"
            "ageron/handson-ml2/master/datasets/titanic/"
        )

        urllib.request.urlretrieve(
            base_url + "train.csv",
            train_path
        )

        urllib.request.urlretrieve(
            base_url + "test.csv",
            test_path
        )

    train_data = pd.read_csv(train_path)
    test_data = pd.read_csv(test_path)

    return train_data, test_data

titanic_train, titanic_test = load_titanic_data()

In [19]:
titanic_train["Sex"] = titanic_train["Sex"].map({
    "male": 1,
    "female": 0
})

In [14]:
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
titanic_train.shape

(891, 12)

In [12]:
titanic_test.shape

(418, 11)

In [20]:
corr_matrix = titanic_train.corr(numeric_only=True)

In [21]:
corr_matrix["Survived"].sort_values(ascending=False)

Survived       1.000000
Fare           0.257307
Parch          0.081629
PassengerId   -0.005007
SibSp         -0.035322
Age           -0.077221
Pclass        -0.338481
Sex           -0.543351
Name: Survived, dtype: float64

In [ ]:
from pandas.plotting import scatter_matrix

attributes = ["", "median_income", "total_rooms",
              "housing_median_age"]
scatter_matrix(titanic_train[attributes], figsize=(12, 8))

In [24]:
null_rows_idx = titanic_train.isnull().any(axis=1)
titanic_train.loc[null_rows_idx].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",1,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",1,2.0,3,1,349909,21.0750,NaN,S